## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
#@ Genuine multi-valued entity: ascending sort uses the normalized MIN per entity.
#@ eOne has names {Yak, apple} -> normalized min "apple"; eTwo has "Beta" -> "beta".
#@ Expect entity order: http://example.org/eOne then .../eTwo  (apple < beta).
#@ Raw bytes would pick eOne's min as "Yak" (0x59) < "Beta" (0x42)? -> eTwo first (wrong).

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/>

SELECT ?s WHERE {
  (?hit ?s ?score) luc:query ("default" "default" "minsel" "" '{"field":"urn:jena:lucene:field#nameSort","order":"asc"}' 100 0) .
}
