# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Facet counts for a search query.
# Shows how results for "copper" distribute across commodity, state, and operator.
# Each row binds (field, value, low, high, count); flat facets leave low/high unbound.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?field ?value ?low ?high ?count
WHERE {
    (?field ?value ?low ?high ?count) luc:facet (
        "default"
        "default"
        "copper"
        '["urn:jena:lucene:field#commodity", "urn:jena:lucene:field#state", "urn:jena:lucene:field#operator"]'
        "null"
        10
        0
    )
}
ORDER BY ?field DESC(?count)
