# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Demonstrates luc:match value binding for a multi-valued identifier field.
# The demo entity has identifiers "", "94130", and "DAG2011/00113216".
# ?matchRaw comes from luc:match rather than luc:query.

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/mining/>

SELECT ?entity ?score ?matchRaw ?identifier
WHERE {
    (?hit ?entity ?score) luc:query ("default" '["urn:jena:lucene:field#identifier"]' "94130" "null" "null" 10) .
    (?hit ?field ?matchRaw) luc:match () .
    ?entity ex:identifier ?identifier .
}
ORDER BY ?identifier
