# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Per-hit field match details using luc:match.
# Searches the title field for "copper" and joins with luc:match
# to retrieve which field matched and its stored value.

PREFIX luc: <urn:jena:lucene:index#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?score ?field ?value
WHERE {
    (?hit ?entity ?score) luc:query ("default" '["urn:jena:lucene:field#title"]' "copper" "null" "null" 10) .
    (?hit ?field ?value) luc:match () .
}
ORDER BY DESC(?score)
