# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Hierarchical facet counts using the state → commodity hierarchy.
# Top-level shows counts per state; drill-down would show commodities within a state.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?field ?value ?low ?high ?count
WHERE {
    (?field ?value ?low ?high ?count) luc:facet ("default" "default" "*" '["urn:jena:lucene:field#state"]' "null" 10 0)
}
ORDER BY ?field DESC(?count)
