# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

PREFIX luc: <urn:jena:lucene:index#>

# Mixed flat and range facets in one query.
# The 5-slot form (?field ?value ?low ?high ?count) is REQUIRED for range facets,
# and works for flat facets too (where ?low and ?high will be null).

SELECT ?field ?value ?low ?high ?count
WHERE {
  (?field ?value ?low ?high ?count) luc:facet (
    "default"
    "default"
    "copper"
    '["urn:jena:lucene:field#state", {"field":"urn:jena:lucene:field#year","ranges":[null, 2020, 2024, null]}]'
    "null"
    20
    0
  ) .
}
ORDER BY ?field ?low ?value
