# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Nested identifier hierarchy counts for Borehole records.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?field ?value ?low ?high ?count
WHERE {
    (?field ?value ?low ?high ?count) luc:facet ("default" "*" '["identifierType_identifierValueExact"]' 20)
}
ORDER BY ?field DESC(?count) ?value
