# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Prefix search across nested identifier values using the flattened text field.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?s ?score
WHERE {
    (?hit ?s ?score) luc:query ("default" '["urn:jena:lucene:field#identifierValueText"]' "bod" "" "" 10 0)
}
ORDER BY DESC(?score) ?s
