# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Sort mining reports by year descending using field-IRI sort syntax.

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/mining/>

SELECT ?entity ?score ?year
WHERE {
    (?hit ?entity ?score) luc:query (
        "default"
        "default"
        "*"
        '{"op":"=","args":[{"property":"urn:jena:lucene:field#entityType"},"http://example.org/mining/MiningReport"]}'
        '{"field":"urn:jena:lucene:field#year","order":"desc"}'
        10
    ) .
    ?entity ex:year ?year .
}

