# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Sort boreholes by depth ascending while still using normal query/facet field IRIs.

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/mining/>

SELECT ?entity ?score ?depth
WHERE {
    (?hit ?entity ?score) luc:query (
        "default"
        "default"
        "*"
        '{"op":"=","args":[{"property":"urn:jena:lucene:field#entityType"},"http://example.org/mining/Borehole"]}'
        '{"field":"urn:jena:lucene:field#depth","order":"asc"}'
        10
    ) .
    ?entity ex:depth ?depth .
}
