# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Correlated exact filter on nested identifier type/value fields.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?s ?score
WHERE {
    (?hit ?s ?score) luc:query (
        "default"
        "default"
        "*"
        '{"op":"and","args":[{"op":"=","args":[{"property":"urn:jena:lucene:field#identifierType"},"company"]},{"op":"=","args":[{"property":"urn:jena:lucene:field#identifierValueExact"},"Newmont"]}]}'
        ""
        10
    )
}
ORDER BY DESC(?score) ?s
