# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Date range filter on idx:DateField using CQL2-JSON between.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?entity ?score
WHERE {
    (?hit ?entity ?score) luc:query (
        "default"
        "default"
        "*"
        '{"op":"and","args":[{"op":"=","args":[{"property":"urn:jena:lucene:field#entityType"},"http://example.org/mining/MiningReport"]},{"op":"between","args":[{"property":"urn:jena:lucene:field#publishedOn"},"2024-01-01","2024-12-31"]}]}'
        '{"field":"urn:jena:lucene:field#publishedOn","order":"desc"}'
        10
    )
}
ORDER BY DESC(?score)
