# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Demonstrates luc:match round-tripping typed boolean literals from stored metadata.

PREFIX luc: <urn:jena:lucene:index#>

SELECT ?entity ?field ?value
WHERE {
    (?hit ?entity ?score) luc:query (
        "default"
        '["urn:jena:lucene:field#qaPassed"]'
        "true"
        ""
        ""
        10
    ) .
    (?hit ?field ?value) luc:match () .
}
