# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

FROM maven:3.9.9-eclipse-temurin-21-alpine AS builder

WORKDIR /build

COPY . .

RUN mvn --batch-mode --quiet --no-transfer-progress -Dstyle.color=never \
    clean package -pl jena-fuseki2/jena-fuseki-server -am -DskipTests -Dmaven.javadoc.skip=true

FROM eclipse-temurin:21-jre-alpine

WORKDIR /fuseki

COPY --from=builder /build/jena-fuseki2/jena-fuseki-server/target/jena-fuseki-server-*.jar ./jena-fuseki-server.jar

ENTRYPOINT ["java", "-jar", "/fuseki/jena-fuseki-server.jar", "--config", "/config/config.ttl"]
