## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
#@ Finding #1 - KEYWORD sort is raw UTF-8 byte order (case-sensitive, NOT locale-collated).
#@ Expect: Apple, Smith, Zebra, apple, banana, Äpfel  (every uppercase before any lowercase; accent last).

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/>

SELECT ?name WHERE {
  (?hit ?s ?score) luc:query ("default" "default" "thing" "" '{"field":"urn:jena:lucene:field#name"}' 100 0) .
  ?s ex:name ?name .
}
