## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
#@ Finding #2b - exact-case "Smith" DOES match (control for 02).
#@ Expect: 1 row -> Smith.

PREFIX luc: <urn:jena:lucene:index#>
PREFIX ex:  <http://example.org/>

SELECT ?name WHERE {
  (?hit ?s ?score) luc:query ("default" "default" "thing"
     '{"op":"=","args":[{"property":"urn:jena:lucene:field#name"},"Smith"]}' "" 100 0) .
  ?s ex:name ?name .
}
