# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
services:
  loader:
    image: ${IMAGE_NAME:-ghcr.io/kurrawong/fuseki-lucene-shacl-loader}:${IMAGE_TAG:-6.1.0-SNAPSHOT}
    volumes:
      - ./config.ttl:/config/config.ttl:ro
      - ./data:/input:ro
      - fuseki-db:/data/DB
      - fuseki-lucene:/data/Lucene
    environment:
      - MODE=${MODE:-all}
      - JAVA_OPTS=-Xmx4g

volumes:
  fuseki-db:
  fuseki-lucene:
