#!/usr/bin/env python3
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
"""
Generate synthetic collar RDF for the collar_ids present in a measurements extract.

The measurements are real (a slice of the GSWA dh_summary_measurements dump); the
collars are invented, because the demo needs *something* on the graph side to join
to and the real collar table is not part of this repo. Everything here is derived
deterministically from the collar id, so regenerating gives byte-identical output.

Usage:
    python3 tools/make-collars.py data/measurements.csv data/collars.ttl
"""

import csv
import io
import random
import sys

COLLAR_NS = "https://linked.data.gov.au/dataset/gswa/collar/"

OPERATORS = [
    "Northern Star Resources", "Rio Tinto Exploration", "BHP Minerals",
    "Gold Fields Australia", "IGO Limited", "Mineral Resources",
    "Sandfire Resources", "De Grey Mining", "Chalice Mining", "Liontown Resources",
]

REGIONS = [
    "Pilbara", "Yilgarn", "Kimberley", "Goldfields-Esperance",
    "Mid West", "Gascoyne", "Great Southern",
]

DRILL_TYPES = ["RC", "Diamond", "Aircore", "RAB", "Percussion"]

STATUSES = ["Completed", "Abandoned", "Suspended"]

# Rough Western Australia bounding box (lon/lat).
LON_MIN, LON_MAX = 113.0, 129.0
LAT_MIN, LAT_MAX = -35.0, -14.0


def collar_ids(measurements_path):
    """Distinct collar ids, in file order."""
    ids = []
    with io.open(measurements_path, encoding="utf-8") as handle:
        reader = csv.reader(handle)
        next(reader)
        for row in reader:
            if not ids or ids[-1] != row[0]:
                ids.append(row[0])
    return ids


def collar_turtle(collar_id):
    # Seed per collar so a given id always produces the same collar, regardless of
    # how many collars are generated or in what order.
    rng = random.Random(int(collar_id))

    operator = rng.choice(OPERATORS)
    region = rng.choice(REGIONS)
    drill_type = rng.choice(DRILL_TYPES)
    status = rng.choice(STATUSES)
    year = rng.randint(1998, 2024)
    depth = round(rng.uniform(30.0, 850.0), 1)
    lon = round(rng.uniform(LON_MIN, LON_MAX), 5)
    lat = round(rng.uniform(LAT_MIN, LAT_MAX), 5)
    prospect = "%s %s" % (rng.choice([
        "Mount", "Lake", "Mount", "Deep", "Black", "Red", "Golden", "Silver",
        "Emu", "Dingo", "Quandong", "Mulga", "Spinifex", "Boulder",
    ]), rng.choice([
        "Well", "Bore", "Rocks", "Creek", "Ridge", "Hill", "Flat", "Soak",
        "Range", "Dam", "Pool", "Gap",
    ]))
    hole_name = "%s %s-%s" % (prospect, drill_type, collar_id[-4:])

    return """
<{ns}{cid}>
    a ex:Collar ;
    rdfs:label {name} ;
    ex:holeId {cid_lit} ;
    ex:prospect {prospect} ;
    ex:operator {operator} ;
    ex:region {region} ;
    ex:drillType {drill_type} ;
    ex:status {status} ;
    ex:yearDrilled {year} ;
    ex:totalDepth {depth} ;
    geo:asWKT "POINT({lon} {lat})"^^geo:wktLiteral .
""".format(
        ns=COLLAR_NS,
        cid=collar_id,
        cid_lit=turtle_string(collar_id),
        name=turtle_string(hole_name),
        prospect=turtle_string(prospect),
        operator=turtle_string(operator),
        region=turtle_string(region),
        drill_type=turtle_string(drill_type),
        status=turtle_string(status),
        year=year,
        depth=depth,
        lon=lon,
        lat=lat,
    )


def turtle_string(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


HEADER = """## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
#
# Synthetic drillhole collars for the external-content demo.
#
# GENERATED by tools/make-collars.py — do not edit by hand.
#
# The collar_id values are real (taken from the GSWA dh_summary_measurements
# extract); everything else on these collars is invented. Each collar joins to its
# measurements purely by IRI: the CSV carries the bare integer, and
# idx:subjectPrefix turns it into the IRI below.

@prefix ex:     <http://example.org/geochem/> .
@prefix geo:    <http://www.opengis.net/ont/geosparql#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
"""


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    measurements_path, output_path = sys.argv[1], sys.argv[2]

    ids = collar_ids(measurements_path)
    with io.open(output_path, "w", encoding="utf-8") as out:
        out.write(HEADER)
        for collar_id in ids:
            out.write(collar_turtle(collar_id))

    print("Wrote %d collars to %s" % (len(ids), output_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
